### ISSUE TITLE
还有一个小问题就是自己设置的网站名什么的会自动全部大写

### ISSUE THREAD

**Issue by jasminecjc** [stiekel/hexo-theme-random#25]
比如自己添加segmentfault的链接，自动大写了，另首页配置的github链接也是自动大写，这样不太合理吧

**Comment by stiekel** [comment]
github 是有对应图标的。
至于没有图标的时候文字链接大写，应该是与字体有关。使用这个字体可能的确欠妥，我尽快换掉。

**Comment by stiekel** [comment]
全部大写是因为使用了这个样式：

```css
#random-index a {
    text-transform: uppercase;
}
```

已经取消了这个样式。
